include:
  - component: git.snpdev.ru/saltpepper/ci-components/pipeline@1.1.0
    inputs:
      services: "backend frontend imgproxy postgres meilisearch"
      required_vars: "DATABASE_HOST DATABASE_PASSWORD DATABASE_NAME DATABASE_USERNAME NEXT_PUBLIC_SITE_URL"
      npm_registry: "https://npm-mirror.gitverse.ru"   # РФ-зеркало (npmjs заблокирован из раннера)
      domain_frontend: boilerplate.snpdev.ru
      domain_backend:  admin.boilerplate.snpdev.ru
      domain_imgproxy: imgproxy.boilerplate.snpdev.ru
      domain_meili:    search.boilerplate.snpdev.ru