NEXT_PUBLIC_APP_ENV=${NEXT_PUBLIC_APP_ENV}
NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
NEXT_PUBLIC_YANDEX_TRACKING_ID=${NEXT_PUBLIC_YANDEX_TRACKING_ID}
PROJECT_SLUG=${PROJECT_SLUG}
DATABASE_URL=${DATABASE_URL}
NOTICES_LIVE_LIMIT=${NOTICES_LIVE_LIMIT}
